version: '3.9'
services:
  prism:
    image: stoplight/prism:4
    platform: linux/amd64
    command: 'mock -h 0.0.0.0 /home/data/sample.yml'
    volumes:
      - ./yml/sample.yml:/home/data/sample.yml
    ports:
      - '4010:4010'